"use client";
/* eslint-disable @next/next/no-img-element -- the original bank-issued QR must remain unchanged */
import { FormEvent, useEffect, useMemo, useState } from "react";
import { BLOCKS } from "../lib/constants";
import { optimizeImageUpload } from "../lib/client-image";
import { DAILY_POOJA_SLOTS, HOMAM_CAPACITY, HOMAM_FEE, POOJA_LABELS, POOJA_TYPES, poojaDate, poojaDateLabel, type PoojaType } from "../lib/pooja";

const UPI_ID="MSHALLMARKSKYRENAFLATOWNERSMAINTENANCEMACSOCIETYLTDCULTURAL.eazypay@icici";
type Child={name:string;age:string};
const initial={poojaType:"" as PoojaType|"",blockNo:"",flatNo:"",residentName:"",phone:"",poojaDate:"",session:"",attendeeCount:"1",paymentReference:"",notes:""};

export function PoojaRegistrationForm(){
  const [form,setForm]=useState(initial);const [children,setChildren]=useState<Child[]>([{name:"",age:""}]);const [proof,setProof]=useState<File|null>(null);const [remaining,setRemaining]=useState(HOMAM_CAPACITY);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [reference,setReference]=useState("");const [copied,setCopied]=useState(false);
  useEffect(()=>{fetch("/api/pooja-registrations?availability=homam",{cache:"no-store"}).then((response)=>response.json()).then((data)=>setRemaining(Number(data.remaining??HOMAM_CAPACITY))).catch(()=>{});},[]);
  const dailySlot=useMemo(()=>DAILY_POOJA_SLOTS.find((slot)=>slot.date===form.poojaDate),[form.poojaDate]);
  function update(name:string,value:string){setForm((current)=>({...current,[name]:value}));}
  function chooseType(type:PoojaType){setError("");setForm((current)=>({...current,poojaType:type,poojaDate:poojaDate(type),session:"",attendeeCount:type==="homam"?"2":"1"}));}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{const data=new FormData();Object.entries(form).forEach(([key,value])=>data.set(key,String(value)));data.set("participantDetails",JSON.stringify(children));if(proof)data.set("paymentProof",await optimizeImageUpload(proof,"homam-payment"));const response=await fetch("/api/pooja-registrations",{method:"POST",body:data});const payload=await response.json() as {error?:string;referenceNo?:string};if(!response.ok)throw new Error(payload.error??"Unable to save the registration.");setReference(payload.referenceNo??"");if(form.poojaType==="homam")setRemaining((value)=>Math.max(0,value-1));window.scrollTo({top:0,behavior:"smooth"});}catch(caught){setError(caught instanceof Error?caught.message:"Unable to save the registration.");}finally{setBusy(false);}}
  async function copyUpi(){await navigator.clipboard.writeText(UPI_ID);setCopied(true);setTimeout(()=>setCopied(false),1800);}
  if(reference)return <section className="wrap pooja-success"><div className="cultural-success"><span>✓</span><div className="eyebrow"><span/>Registration received</div><h2>Thank you</h2><p>Your {form.poojaType&&POOJA_LABELS[form.poojaType]} registration has been recorded.</p><div><small>Reference number</small><strong>{reference}</strong></div><button className="button primary" onClick={()=>{setReference("");setForm(initial);setChildren([{name:"",age:""}]);setProof(null);}}>Register Another Pooja</button></div></section>;
  return <><section className="page-intro wrap pooja-intro"><div><div className="eyebrow"><span/>Ganesh Chaturthi 2026</div><h1>Pooja Registration</h1><p>Select a Pooja and register your household. You may submit separate registrations for different Poojas or sessions.</p></div><aside><strong>Homam availability</strong><b>{remaining} of {HOMAM_CAPACITY}</b><span>slots remaining · ₹{HOMAM_FEE.toLocaleString("en-IN")} per couple</span></aside></section>
    <section className="wrap pooja-shell"><div className="pooja-choice-grid">{POOJA_TYPES.map((type)=><button type="button" className={form.poojaType===type?"selected":""} key={type} onClick={()=>chooseType(type)}><span>{type==="daily"?"01":type==="saraswathi"?"03":type==="lakshmi"?"05":"06"}</span><strong>{POOJA_LABELS[type]}</strong><small>{type==="daily"?"Days 1–6 · choose a session":type==="saraswathi"?"Day 3 · children’s registration":type==="lakshmi"?"Day 5 · household registration":`Day 6 · ₹${HOMAM_FEE.toLocaleString("en-IN")} · ${remaining} slots left`}</small></button>)}</div>
    {!form.poojaType?<div className="empty-state"><p>Select a Pooja above to continue.</p></div>:form.poojaType==="homam"&&remaining===0?<div className="pooja-full"><h2>Homam registrations are full</h2><p>All {HOMAM_CAPACITY} available entries have been reserved.</p></div>:<form className="pooja-form" onSubmit={submit}>
      <header><div><span className="card-kicker">{POOJA_LABELS[form.poojaType]}</span><h2>{form.poojaType==="homam"?"Reserve a Homam entry":"Register your household"}</h2></div>{form.poojaType!=="daily"&&<strong>{poojaDateLabel(poojaDate(form.poojaType))}</strong>}</header>
      <fieldset><div className="pooja-section-heading"><span>1</span><h3>Household Details</h3></div><div className="field-grid"><label>Block <b>*</b><select required value={form.blockNo} onChange={(event)=>update("blockNo",event.target.value)}><option value="" disabled>Select block</option>{BLOCKS.map((block)=><option key={block} value={block}>Block {block}</option>)}</select></label><label>Flat Number <b>*</b><input required value={form.flatNo} onChange={(event)=>update("flatNo",event.target.value.toUpperCase().replace(/[\s-]/g,""))} onBlur={()=>update("flatNo",normalizeFlat(form.flatNo,form.blockNo))} placeholder="e.g. 505 or C505"/><small>You may include the selected block letter.</small></label><label>{form.poojaType==="homam"?"Participating Couple’s Name(s)":"Resident Name"} <b>*</b><input required maxLength={120} value={form.residentName} onChange={(event)=>update("residentName",event.target.value)}/></label><label>Mobile Number <b>*</b><span className="phone-field"><i>+91</i><input required inputMode="numeric" pattern="[0-9]{10}" maxLength={10} value={form.phone} onChange={(event)=>update("phone",event.target.value.replace(/\D/g,"").slice(0,10))}/></span></label></div></fieldset>
      <fieldset><div className="pooja-section-heading"><span>2</span><h3>Pooja Details</h3></div>{form.poojaType==="daily"?<div className="field-grid"><label>Pooja Date <b>*</b><select required value={form.poojaDate} onChange={(event)=>{update("poojaDate",event.target.value);update("session","");}}><option value="" disabled>Select date</option>{DAILY_POOJA_SLOTS.map((slot)=><option key={slot.date} value={slot.date}>Day {slot.day} · {poojaDateLabel(slot.date)}</option>)}</select></label><label>Session <b>*</b><select required value={form.session} disabled={!dailySlot} onChange={(event)=>update("session",event.target.value)}><option value="" disabled>Select session</option>{dailySlot?.sessions.map((session)=><option key={session} value={session}>{title(session)}</option>)}</select></label><label>Number of Attendees <b>*</b><input required type="number" min={1} max={20} value={form.attendeeCount} onChange={(event)=>update("attendeeCount",event.target.value)}/></label></div>:form.poojaType==="saraswathi"?<div className="pooja-children"><p>Add every participating child. The total is calculated automatically.</p>{children.map((child,index)=><div key={index}><label>Child {index+1} Name <b>*</b><input required value={child.name} onChange={(event)=>setChildren(children.map((item,itemIndex)=>itemIndex===index?{...item,name:event.target.value}:item))}/></label><label>Age <b>*</b><input required type="number" min={1} max={18} value={child.age} onChange={(event)=>setChildren(children.map((item,itemIndex)=>itemIndex===index?{...item,age:event.target.value}:item))}/></label>{children.length>1&&<button type="button" onClick={()=>setChildren(children.filter((_,itemIndex)=>itemIndex!==index))}>Remove</button>}</div>)}{children.length<10&&<button type="button" className="button quiet" onClick={()=>setChildren([...children,{name:"",age:""}])}>+ Add Another Child</button>}<strong>{children.length} child{children.length===1?"":"ren"} in this registration</strong></div>:form.poojaType==="lakshmi"?<label className="pooja-attendees">Number of Attendees <b>*</b><input required type="number" min={1} max={20} value={form.attendeeCount} onChange={(event)=>update("attendeeCount",event.target.value)}/></label>:<div className="homam-note"><strong>One registration reserves one entry for a couple.</strong><span>The participation fee is ₹{HOMAM_FEE.toLocaleString("en-IN")}.</span></div>}<label className="pooja-notes">Notes <small>optional</small><textarea maxLength={500} value={form.notes} onChange={(event)=>update("notes",event.target.value)} placeholder="Any information the Pooja committee should know"/></label></fieldset>
      {form.poojaType==="homam"&&<fieldset><div className="pooja-section-heading"><span>3</span><h3>Payment Details</h3></div><section className="pooja-payment-card"><div><span className="card-kicker">Official festival UPI</span><h3>Pay ₹{HOMAM_FEE.toLocaleString("en-IN")}</h3><p>Confirm that the recipient name contains Hallmark Skyrena and Cultural before paying.</p><strong>{UPI_ID}</strong><button type="button" className="button quiet" onClick={()=>void copyUpi()}>{copied?"UPI ID Copied ✓":"Copy UPI ID"}</button></div><a href="/hallmark-skyrena-upi-qr.png" target="_blank" rel="noreferrer"><img src="/hallmark-skyrena-upi-qr.png" alt="Official Hallmark Skyrena cultural account UPI QR code"/><strong>Tap to view full size</strong></a></section><div className="field-grid"><label>UPI Transaction Reference <small>optional</small><input maxLength={80} value={form.paymentReference} onChange={(event)=>update("paymentReference",event.target.value)} /></label><label>Payment Confirmation Image <b>*</b><input required type="file" accept="image/jpeg,image/png,image/webp" onChange={(event)=>setProof(event.target.files?.[0]??null)}/><small>Use Camera or Photo Library on mobile. Images are stored privately.</small></label></div></fieldset>}
      {error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary pooja-submit" disabled={busy}>{busy?"Submitting…":form.poojaType==="homam"?"Submit and Reserve Homam Entry":"Submit Pooja Registration"}</button>
    </form>}</section></>;
}

function normalizeFlat(flatNo:string,blockNo:string){const flat=flatNo.trim().toUpperCase().replace(/[\s-]+/g,"");const block=blockNo.trim().toUpperCase();return block&&flat.startsWith(block)&&/^(?:G|\d)/.test(flat.slice(block.length))?flat.slice(block.length):flat;}
function title(value:string){return value.charAt(0).toUpperCase()+value.slice(1);}
