"use client";

import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { BLOCKS, currency } from "../lib/constants";

type Flat={id:string;blockNo:string;flatNo:string;residentName:string;occupancy:string;visitStatus:string;visitNotes:string;donated:number;donationAmount:number;referenceNo:string|null};
type User={role:"admin"|"block";blockNo:string|null};
type CsvFlat={flatNo:string;residentName:string;occupancy:string};

export function FlatStatusMap(){
  const[flats,setFlats]=useState<Flat[]>([]);const[user,setUser]=useState<User|null>(null);const[block,setBlock]=useState("");const[selected,setSelected]=useState<Flat|null>(null);const[error,setError]=useState("");const[message,setMessage]=useState("");const[csvRows,setCsvRows]=useState<CsvFlat[]>([]);const[csvName,setCsvName]=useState("");const[importing,setImporting]=useState(false);const[masterFlatNo,setMasterFlatNo]=useState("");const[masterResidentName,setMasterResidentName]=useState("");const[masterOccupancy,setMasterOccupancy]=useState("");const[masterBusy,setMasterBusy]=useState(false);
  const apply=useCallback((body:{flats:Flat[];user:User;block:string})=>{setFlats(body.flats);setUser(body.user);setBlock(body.block);setSelected((current)=>body.flats.find((flat)=>flat.id===current?.id)??null);},[]);
  const load=useCallback(async(requested?:string)=>{const response=await fetch(`/api/flats/map${requested?`?block=${requested}`:""}`);const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to load occupied flats.");apply(body);},[apply]);
  useEffect(()=>{let active=true;fetch("/api/flats/map").then(async(response)=>({response,body:await response.json()})).then(({response,body})=>{if(!active)return;if(!response.ok)setError(body.error??"Unable to load occupied flats.");else apply(body);}).catch(()=>active&&setError("Unable to load occupied flats."));return()=>{active=false;};},[apply]);
  const floors=useMemo(()=>groupFloors(flats),[flats]);const donatedCount=flats.filter((flat)=>Boolean(flat.donated)).length;const optedOutCount=flats.filter((flat)=>!flat.donated&&flat.visitStatus==="opted_out").length;const pendingCount=flats.length-donatedCount-optedOutCount;
  async function chooseFile(event:ChangeEvent<HTMLInputElement>){setError("");setMessage("");setCsvRows([]);const file=event.target.files?.[0];if(!file){setCsvName("");return;}try{const rows=parseCsv(await file.text());setCsvRows(rows);setCsvName(file.name);}catch(caught){setCsvName("");setError(caught instanceof Error?caught.message:"Unable to read CSV file.");event.target.value="";}}
  async function importCsv(){if(!csvRows.length||!block)return;setImporting(true);setError("");setMessage("");try{const response=await fetch("/api/admin/flats/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({blockNo:block,flats:csvRows})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to import occupied flats.");setMessage(`${body.imported} occupied flats imported for Block ${body.blockNo}.`);setCsvRows([]);setCsvName("");await load(block);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to import occupied flats.");}finally{setImporting(false);}}
  async function saveMasterFlat(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!masterFlatNo.trim()||!block)return;setMasterBusy(true);setError("");setMessage("");try{const response=await fetch("/api/flats",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({blockNo:block,flatNo:masterFlatNo,residentName:masterResidentName,occupancy:masterOccupancy})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to update the occupied-flat master.");setMessage(`Flat ${body.flatNo} is now in the Block ${body.blockNo} occupied-flat master.`);setMasterFlatNo("");setMasterResidentName("");setMasterOccupancy("");await load(block);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to update the occupied-flat master.");}finally{setMasterBusy(false);}}
  async function removeMasterFlat(){const flatNo=masterFlatNo.trim().toUpperCase();if(!flatNo||!block)return;if(!window.confirm(`Remove Flat ${flatNo} from the Block ${block} occupied-flat master? Donation and visit history will be preserved.`))return;setMasterBusy(true);setError("");setMessage("");try{const response=await fetch("/api/flats",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({blockNo:block,flatNo})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to remove the occupied flat.");setMessage(`Flat ${body.flatNo} was removed from the Block ${body.blockNo} occupied-flat master.`);setMasterFlatNo("");setMasterResidentName("");setMasterOccupancy("");setSelected(null);await load(block);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to remove the occupied flat.");}finally{setMasterBusy(false);}}
  function chooseMasterFlat(flat:Flat){setSelected(flat);setMasterFlatNo(flat.flatNo);setMasterResidentName(flat.residentName);setMasterOccupancy(flat.occupancy);}
  return <section className="wrap flat-map-shell"><div className="workspace-heading"><div><div className="eyebrow"><span/>Collection overview</div><h1>Flat Status Map</h1><p>A block-wise view of occupied homes and their current donation status.</p></div>{user?.role==="admin"&&<label className="map-block-picker">Viewing Block<select value={block} onChange={(event)=>{setSelected(null);setMasterFlatNo("");setMasterResidentName("");setMasterOccupancy("");void load(event.target.value);}}>{BLOCKS.map((item)=><option key={item}>{item}</option>)}</select></label>}</div>
    {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success">{message}</p>}
    {user?.role==="admin"&&<section className="csv-import-card"><div><span className="card-kicker">Occupied-flat master</span><h2>Upload Block {block} CSV</h2><p>Uploading replaces the occupied-flat list for this block. Existing donations and visit history are preserved.</p></div><div className="csv-controls"><label className="csv-file">Choose CSV<input type="file" accept=".csv,text/csv" onChange={(event)=>void chooseFile(event)}/><small>{csvName?`${csvName} · ${csvRows.length} valid flats`:"Required: flat_no. Optional: resident_name, occupancy (owner or tenant)."}</small></label><div className="csv-actions"><button className="button primary" disabled={!csvRows.length||importing} onClick={()=>void importCsv()}>{importing?"Importing…":`Import ${csvRows.length||""} Flats`}</button><button className="button quiet" onClick={downloadTemplate}>Download Template</button></div></div></section>}
    {user&&<section className="flat-master-card"><div><span className="card-kicker">Manage occupied-flat master</span><h2>Add, rename or remove a flat</h2><p>{user.role==="block"?`Changes are restricted to Block ${block}.`:"Choose a block above, then maintain individual flats here."} Select a tile below to edit it quickly.</p></div><form className="flat-master-form" onSubmit={saveMasterFlat}><label>Flat Number<input required value={masterFlatNo} onChange={(event)=>setMasterFlatNo(event.target.value.toUpperCase())} placeholder="e.g. G01 or 101"/></label><label><span className="field-label">Resident Name <span className="optional">optional</span></span><input value={masterResidentName} onChange={(event)=>setMasterResidentName(event.target.value)} placeholder="Resident name"/></label><label><span className="field-label">Occupancy <span className="optional">optional</span></span><select value={masterOccupancy} onChange={(event)=>setMasterOccupancy(event.target.value)}><option value="">Not recorded</option><option value="owner">Owner</option><option value="tenant">Tenant</option></select></label><div className="flat-master-buttons"><button className="button primary" disabled={masterBusy}>{masterBusy?"Saving…":"Add / Update Flat"}</button><button type="button" className="button quiet danger-button" disabled={masterBusy||!masterFlatNo.trim()} onClick={()=>void removeMasterFlat()}>Remove Flat</button></div></form></section>}
    <div className="flat-map-summary"><div><strong>Block {block}</strong><span>{flats.length} occupied flats</span></div><div className="flat-legend"><span><i className="donated"/>Donated ({donatedCount})</span><span><i className="revisit"/>Visit again</span><span><i className="opted-out"/>Opted out ({optedOutCount})</span><span><i className="pending"/>Pending ({pendingCount})</span></div></div>
    <div className="flat-map-layout"><div className="building-map" aria-label={`Occupied flats in Block ${block}`}>{floors.map(([floor,items])=><section className="floor-row" key={floor}><header><span>Floor</span><strong>{floor}</strong></header><div className="flat-tile-grid">{items.map((flat)=>{const state=flat.donated?"donated":flat.visitStatus==="opted_out"?"opted-out":flat.visitStatus==="visit_again"?"revisit":"pending";return <button key={flat.id} aria-label={`Flat ${flat.flatNo}, ${state}`} className={`flat-tile ${state} ${selected?.id===flat.id?"selected":""}`} onClick={()=>chooseMasterFlat(flat)}><span>{flat.donated?"✓":flat.visitStatus==="opted_out"?"—":""}</span><strong>{flat.flatNo}</strong></button>;})}</div></section>)}{!flats.length&&<div className="flat-map-empty"><strong>No occupied flats recorded for Block {block}.</strong><p>Add a flat above{user?.role==="admin"?" or upload the block CSV":""}.</p></div>}</div>
      <aside className={`flat-map-detail ${selected?"":"empty"}`}>{selected?<><span className="card-kicker">Flat details</span><h2>Flat {selected.flatNo}</h2><span className={`map-status ${selected.donated?"donated":selected.visitStatus==="opted_out"?"opted-out":selected.visitStatus==="visit_again"?"revisit":"pending"}`}>{selected.donated?"Donation recorded":selected.visitStatus==="opted_out"?"Opted out · do not visit":selected.visitStatus==="visit_again"?"Visit again":"Donation pending"}</span><dl><div><dt>Block</dt><dd>{selected.blockNo}</dd></div><div><dt>Resident</dt><dd>{selected.residentName||"Not provided"}</dd></div><div><dt>Occupancy</dt><dd>{selected.occupancy?selected.occupancy[0].toUpperCase()+selected.occupancy.slice(1):"Not recorded"}</dd></div>{Boolean(selected.donated)&&<><div><dt>Amount</dt><dd>{currency(Number(selected.donationAmount))}</dd></div><div><dt>Reference</dt><dd>{selected.referenceNo||"—"}</dd></div></>}<div><dt>Visit notes</dt><dd>{selected.visitNotes||"—"}</dd></div></dl></>:<><span aria-hidden="true">⌂</span><p>Select a flat to view its details.</p></>}</aside>
    </div></section>;
}

function groupFloors(flats:Flat[]){const groups=new Map<string,Flat[]>();const sorted=[...flats].sort((a,b)=>a.flatNo.localeCompare(b.flatNo,undefined,{numeric:true}));for(const flat of sorted){const flatNo=flat.flatNo.trim().toUpperCase();const match=flatNo.match(/(\d{3,4})$/);const floor=flatNo.startsWith("G")?"G":match?String(Number(match[1].slice(0,-2))):"Other";groups.set(floor,[...(groups.get(floor)??[]),flat]);}return [...groups.entries()].sort(([a],[b])=>floorOrder(a)-floorOrder(b)||a.localeCompare(b,undefined,{numeric:true}));}
function floorOrder(floor:string){return floor==="G"?-1:floor==="Other"?Number.MAX_SAFE_INTEGER:Number(floor);}
function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter((line)=>line.trim());if(lines.length<2)throw new Error("The CSV must include a header and at least one occupied flat.");const rows=lines.map(parseCsvLine);const headers=rows[0].map((header)=>header.trim().toLowerCase().replace(/[\s-]+/g,"_"));const flatIndex=headers.findIndex((header)=>["flat_no","flat_number","flat"].includes(header));const residentIndex=headers.findIndex((header)=>["resident_name","resident","name"].includes(header));const occupancyIndex=headers.findIndex((header)=>["occupancy","occupant_type","owner_tenant"].includes(header));if(flatIndex<0)throw new Error("CSV requires a flat_no column.");const seen=new Set<string>();return rows.slice(1).map((row)=>{const occupancy=occupancyIndex>=0?(row[occupancyIndex]??"").trim().toLowerCase():"";return{flatNo:(row[flatIndex]??"").trim().toUpperCase(),residentName:residentIndex>=0?(row[residentIndex]??"").trim():"",occupancy:["owner","tenant"].includes(occupancy)?occupancy:""};}).filter((row)=>row.flatNo&&!seen.has(row.flatNo)&&Boolean(seen.add(row.flatNo)));}
function parseCsvLine(line:string){const cells:string[]=[];let value="";let quoted=false;for(let index=0;index<line.length;index++){const character=line[index];if(character==='"'&&quoted&&line[index+1]==='"'){value+='"';index++;}else if(character==='"'){quoted=!quoted;}else if(character===","&&!quoted){cells.push(value);value="";}else value+=character;}cells.push(value);return cells;}
function downloadTemplate(){const blob=new Blob(["flat_no,resident_name,occupancy\n101,,owner\n102,,tenant\n"],{type:"text/csv"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="occupied-flats-template.csv";anchor.click();URL.revokeObjectURL(url);}
