"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { HOMAM_CAPACITY, POOJA_LABELS, POOJA_TYPES, poojaDateLabel, type PoojaType } from "../lib/pooja";

type Row={id:string;referenceNo:string;poojaType:PoojaType;poojaDate:string;session:string;blockNo:string;flatNo:string;residentName:string;phone:string;attendeeCount:number;participantDetails:string;paymentAmount:number;paymentReference:string;hasProof:number;paymentStatus:string;status:string;notes:string;createdAt:string};
type User={role:"admin"|"block"|"cultural";blockNo:string|null};
export function PoojaDashboard(){
  const [rows,setRows]=useState<Row[]>([]);const [user,setUser]=useState<User|null>(null);const [filter,setFilter]=useState("");const [type,setType]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/pooja-registrations",{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Unable to load Pooja registrations.");setRows(payload.registrations??[]);setUser(payload.user??null);},[]);
  useEffect(()=>{const timeout=window.setTimeout(()=>void load().catch((caught)=>setError(caught instanceof Error?caught.message:"Unable to load registrations.")),0);return()=>window.clearTimeout(timeout);},[load]);
  const visible=useMemo(()=>rows.filter((row)=>(!type||row.poojaType===type)&&`${row.referenceNo} ${row.residentName} ${row.blockNo} ${row.flatNo} ${row.phone}`.toLowerCase().includes(filter.toLowerCase())),[rows,type,filter]);
  const exportUrl=useMemo(()=>{const params=new URLSearchParams();if(filter.trim())params.set("q",filter.trim());if(type)params.set("type",type);return `/api/pooja-registrations/export?${params}`;},[filter,type]);
  const active=rows.filter((row)=>row.status!=="cancelled");const homam=active.filter((row)=>row.poojaType==="homam");
  function printRegistrations(){document.body.classList.add("printing-pooja-plan");const cleanup=()=>document.body.classList.remove("printing-pooja-plan");window.addEventListener("afterprint",cleanup,{once:true});window.print();window.setTimeout(cleanup,1500);}
  async function update(id:string,values:Record<string,string>){setBusy(id);setError("");try{const response=await fetch("/api/pooja-registrations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...values})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Unable to update registration.");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Unable to update registration.");}finally{setBusy("");}}
  return <section className="wrap pooja-dashboard"><header className="workspace-heading"><div><div className="eyebrow"><span/>Pooja coordination workspace</div><h1>Pooja Registrations</h1><p>Track household registrations, attendees and Homam payment verification.</p></div><a className="button primary" href="/pooja-registration">+ New Registration</a></header>
    <div className="pooja-stat-grid"><article><span>Total active registrations</span><strong>{active.length}</strong></article><article><span>Total attendees</span><strong>{active.reduce((sum,row)=>sum+Number(row.attendeeCount),0)}</strong></article><article><span>Saraswathi Pooja children</span><strong>{active.filter((row)=>row.poojaType==="saraswathi").reduce((sum,row)=>sum+Number(row.attendeeCount),0)}</strong></article><article><span>Homam entries</span><strong>{homam.length} / {HOMAM_CAPACITY}</strong></article></div>
    <div className="workspace-toolbar pooja-toolbar no-print"><input value={filter} onChange={(event)=>setFilter(event.target.value)} placeholder="Search name, flat, mobile or reference"/><select value={type} onChange={(event)=>setType(event.target.value)}><option value="">All Poojas</option>{POOJA_TYPES.map((item)=><option key={item} value={item}>{POOJA_LABELS[item]}</option>)}</select><strong>{visible.length} registration(s)</strong><a className={`button quiet${visible.length?"":" disabled"}`} href={visible.length?exportUrl:undefined}>Download Excel</a><button className="button quiet" disabled={!visible.length} onClick={printRegistrations}>Download / Print PDF</button></div>
    {error&&<p className="form-error">{error}</p>}<div className="pooja-registration-grid">{visible.map((row)=><article className={row.status==="cancelled"?"cancelled":""} key={row.id}><header><div><span className={`status ${row.status}`}>{row.status}</span><small>{row.referenceNo}</small></div><strong>{POOJA_LABELS[row.poojaType]}</strong></header><h2>{row.residentName}</h2><p>Block {row.blockNo} · Flat {row.flatNo}</p><dl><div><dt>Date</dt><dd>{poojaDateLabel(row.poojaDate)}{row.session?` · ${title(row.session)}`:""}</dd></div><div><dt>Attendees</dt><dd>{row.attendeeCount}</dd></div><div><dt>Mobile</dt><dd><a href={`tel:+91${row.phone}`}>+91 {row.phone}</a></dd></div>{row.poojaType==="saraswathi"&&<div><dt>Children</dt><dd>{children(row.participantDetails)}</dd></div>}{row.poojaType==="homam"&&<><div><dt>Fee</dt><dd>₹{Number(row.paymentAmount).toLocaleString("en-IN")}</dd></div><div><dt>Payment</dt><dd>{title(row.paymentStatus)}</dd></div><div><dt>UPI reference</dt><dd>{row.paymentReference||"Not provided"}</dd></div></>}</dl>{row.notes&&<blockquote>{row.notes}</blockquote>}<div className="card-actions">{row.poojaType==="homam"&&row.hasProof&&user?.role!=="cultural"&&<a className="button quiet" href={`/api/pooja-registrations/proof/${row.id}`} target="_blank">View Payment Proof</a>}{user?.role==="admin"&&row.poojaType==="homam"&&row.paymentStatus!=="verified"&&<button className="button primary" disabled={busy===row.id} onClick={()=>void update(row.id,{paymentStatus:"verified"})}>Verify Payment</button>}{user?.role==="admin"&&row.status!=="cancelled"&&<button className="button quiet" disabled={busy===row.id} onClick={()=>void update(row.id,{status:"cancelled"})}>Cancel Registration</button>}{user?.role==="admin"&&row.status==="cancelled"&&<button className="button quiet" disabled={busy===row.id} onClick={()=>void update(row.id,{status:"submitted"})}>Restore</button>}</div></article>)}{!visible.length&&<div className="empty-state"><p>No registrations match the selected filters.</p></div>}</div>
  </section>;
}
function title(value:string){return value.charAt(0).toUpperCase()+value.slice(1).replaceAll("_"," ");}
function children(value:string){try{const parsed=JSON.parse(value) as Array<{name:string;age:number}>;return parsed.map((item)=>`${item.name} (${item.age})`).join(", ");}catch{return "Not recorded";}}
