"use client";

import { FormEvent, useEffect, useState } from "react";
import { BLOCKS } from "../../lib/constants";

const initial={blockNo:"",flatNo:"",name:"",age:"",phone:""};

export function FancyDressRegistrationForm(){
  const [form,setForm]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [reference,setReference]=useState("");const [closed,setClosed]=useState<boolean|null>(null);
  useEffect(()=>{fetch("/api/cultural/fancy-dress",{cache:"no-store"}).then((response)=>response.json()).then((payload)=>setClosed(Boolean(payload.closed))).catch(()=>setClosed(false));},[]);
  function update(name:keyof typeof initial,value:string){setForm((current)=>({...current,[name]:value}));}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/cultural/fancy-dress",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const payload=await response.json() as {error?:string;referenceNo?:string};if(!response.ok)throw new Error(payload.error??"Unable to save the Fancy Dress registration.");setReference(payload.referenceNo??"");window.scrollTo({top:0,behavior:"smooth"});}catch(caught){setError(caught instanceof Error?caught.message:"Unable to save the Fancy Dress registration.");}finally{setBusy(false);}}
  if(reference)return <section className="wrap fancy-dress-shell"><div className="cultural-success"><span>✓</span><p className="card-kicker">Registration received</p><h2>See you at Fancy Dress!</h2><p>The Cultural Committee has received the participant’s details.</p><div><small>Registration reference</small><strong>{reference}</strong></div><button className="button primary" onClick={()=>{setReference("");setForm(initial);}}>Register Another Participant</button></div></section>;
  if(closed===null)return <section className="wrap fancy-dress-shell"><div className="admin-card empty-state"><p>Checking registration availability…</p></div></section>;
  if(closed)return <section className="wrap fancy-dress-shell"><div className="cultural-success cultural-registration-closed"><span aria-hidden="true">—</span><p className="card-kicker">Registration update</p><h2>Fancy Dress registrations are closed</h2><p>The last date for registration was 13 September 2026. Thank you for your interest.</p></div></section>;
  return <section className="wrap fancy-dress-shell"><form className="fancy-dress-form" onSubmit={submit}><div className="fancy-dress-note"><span className="card-kicker">Programme details</span><strong>Thursday, 17 September 2026 · 7:00 PM onwards</strong><p>Please submit one registration for each participant. All fields are mandatory.</p></div><fieldset><h2 className="cultural-section-heading"><span>1</span>Participant Details</h2><div className="field-grid"><label><span className="cultural-field-label">Block <b>*</b></span><select required value={form.blockNo} onChange={(event)=>update("blockNo",event.target.value)}><option value="" disabled>Select block</option>{BLOCKS.map((block)=><option key={block} value={block}>Block {block}</option>)}</select></label><label><span className="cultural-field-label">Flat Number <b>*</b></span><input required maxLength={10} value={form.flatNo} onChange={(event)=>update("flatNo",event.target.value.toUpperCase().replace(/[\s-]/g,""))} onBlur={()=>update("flatNo",normalizeFlat(form.flatNo,form.blockNo))} placeholder="e.g. 505 or C505"/><small>You may include the selected block letter.</small></label><label><span className="cultural-field-label">Participant Name <b>*</b></span><input required maxLength={100} value={form.name} onChange={(event)=>update("name",event.target.value)}/></label><label><span className="cultural-field-label">Age <b>*</b></span><input required type="number" min={1} max={100} inputMode="numeric" value={form.age} onChange={(event)=>update("age",event.target.value)}/></label><label className="wide"><span className="cultural-field-label">Mobile Number <b>*</b></span><span className="phone-field"><i>+91</i><input required type="tel" inputMode="numeric" pattern="[0-9]{10}" maxLength={10} value={form.phone} placeholder="10-digit number" onChange={(event)=>update("phone",event.target.value.replace(/\D/g,"").slice(0,10))}/></span></label></div></fieldset>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary cultural-submit" disabled={busy}>{busy?"Submitting…":"Submit Fancy Dress Registration"}</button><p className="fancy-dress-deadline">Last date for registration: Sunday, 13 September 2026.</p></form></section>;
}

function normalizeFlat(flatNo:string,blockNo:string){const flat=flatNo.trim().toUpperCase().replace(/[\s-]+/g,"");const block=blockNo.trim().toUpperCase();return block&&flat.startsWith(block)&&/^(?:G|\d)/.test(flat.slice(block.length))?flat.slice(block.length):flat;}
