"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { BLOCKS, MINIMUM_DONATION, currency } from "../lib/constants";
type User={role:"admin"|"block";blockNo:string|null}; type Success={referenceNo:string};
const blank={residentName:"",blockNo:"",flatNo:"",gotram:"",occupancy:"owner",phone:"",mainDonation:"2000",annadaanamDonation:"0",adultCount:"0",childCount:"0",paymentReference:"",notes:"",publicNameConsent:false};
const MAX_STORED_PROOF_BYTES=1024*1024;
async function canvasBlob(canvas:HTMLCanvasElement,quality:number){return new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",quality));}
async function optimizePaymentProof(file:File){
  if(file.size<=MAX_STORED_PROOF_BYTES)return file;
  const bitmap=await createImageBitmap(file);let width=bitmap.width;let height=bitmap.height;
  const initialScale=Math.min(1,1600/Math.max(width,height));width=Math.max(1,Math.round(width*initialScale));height=Math.max(1,Math.round(height*initialScale));
  const canvas=document.createElement("canvas");const context=canvas.getContext("2d");if(!context){bitmap.close();throw new Error("This browser cannot optimize the selected image.");}
  let blob:Blob|null=null;
  for(const quality of [0.82,0.7,0.58]){canvas.width=width;canvas.height=height;context.drawImage(bitmap,0,0,width,height);blob=await canvasBlob(canvas,quality);if(blob&&blob.size<=MAX_STORED_PROOF_BYTES)break;if(blob){const scale=Math.min(0.9,Math.sqrt(MAX_STORED_PROOF_BYTES/blob.size)*0.9);width=Math.max(1,Math.round(width*scale));height=Math.max(1,Math.round(height*scale));}}
  bitmap.close();if(!blob||blob.size>MAX_STORED_PROOF_BYTES)throw new Error("The payment image is still too large. Please take a screenshot or crop it and try again.");
  return new File([blob],`${file.name.replace(/\.[^.]+$/,"")||"payment-proof"}.webp`,{type:"image/webp",lastModified:Date.now()});
}
export function ContributionForm(){const[form,setForm]=useState(blank);const[user,setUser]=useState<User|null>(null);const[proof,setProof]=useState<File|null>(null);const[optimizing,setOptimizing]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState<Success|null>(null);
useEffect(()=>{fetch("/api/auth/me").then(r=>r.json()).then((u:User)=>{setUser(u);if(u.role==="block")setForm(x=>({...x,blockNo:u.blockNo??""}));}).catch(()=>setError("Unable to load your access profile."));},[]);
const total=useMemo(()=>Number(form.mainDonation||0)+Number(form.annadaanamDonation||0),[form.mainDonation,form.annadaanamDonation]);function update(name:string,value:string|boolean){setForm(x=>({...x,[name]:value}));}
async function selectProof(file:File|null){setProof(null);setError("");if(!file)return;setOptimizing(true);try{setProof(await optimizePaymentProof(file));}catch(c){setError(c instanceof Error?c.message:"Unable to optimize the payment image.");}finally{setOptimizing(false);}}
async function submit(e:FormEvent){e.preventDefault();if(!proof){setError("Capture or upload the UPI payment confirmation.");return;}setBusy(true);setError("");try{const data=new FormData();Object.entries(form).forEach(([k,v])=>data.set(k,String(v)));data.set("paymentProof",proof);const r=await fetch("/api/registrations",{method:"POST",body:data});const p=await r.json();if(!r.ok)throw new Error(p.error??"Submission failed.");setSuccess(p);window.scrollTo({top:0,behavior:"smooth"});}catch(c){setError(c instanceof Error?c.message:"Please try again.");}finally{setBusy(false);}}
if(success)return <section className="wrap compact success-panel"><div className="success-icon">✓</div><div className="eyebrow"><span/>Donation recorded</div><h2>Payment submitted for verification.</h2><div className="reference-card"><small>Reference number</small><strong>{success.referenceNo}</strong></div><button className="button quiet" onClick={()=>{setSuccess(null);setProof(null);setForm({...blank,blockNo:user?.blockNo??""});}}>Add another donation</button></section>;
return <form className="wrap form-shell" onSubmit={submit}><div className="form-main"><fieldset><legend><span>1</span>Household details</legend><div className="field-grid">
<label className="wide">Resident name<input required name="residentName" value={form.residentName} onChange={e=>update(e.target.name,e.target.value)}/></label>
<label>Block<select required name="blockNo" disabled={user?.role==="block"} value={form.blockNo} onChange={e=>update(e.target.name,e.target.value)}><option value="">Choose</option>{BLOCKS.map(b=><option key={b}>{b}</option>)}</select><small>{user?.role==="block"?`Locked to Block ${user.blockNo}`:"Admins may select any block"}</small></label>
<label>Flat number<input required name="flatNo" value={form.flatNo} onChange={e=>update(e.target.name,e.target.value)}/></label><label>Gotram<input required name="gotram" value={form.gotram} onChange={e=>update(e.target.name,e.target.value)}/></label><label>Occupancy<select name="occupancy" value={form.occupancy} onChange={e=>update(e.target.name,e.target.value)}><option value="owner">Owner</option><option value="tenant">Tenant</option></select></label><label className="wide">Phone <span className="optional">optional</span><input name="phone" inputMode="tel" value={form.phone} onChange={e=>update(e.target.name,e.target.value)}/></label></div></fieldset>
<fieldset><legend><span>2</span>UPI contribution</legend><div className="field-grid"><label>Festival donation<input required name="mainDonation" type="number" inputMode="numeric" min={MINIMUM_DONATION} step="100" value={form.mainDonation} onChange={e=>update(e.target.name,e.target.value)}/><small>Minimum and default ₹2,000</small></label><label>Extra Annadaanam<input name="annadaanamDonation" type="number" min="0" step="100" value={form.annadaanamDonation} onChange={e=>update(e.target.name,e.target.value)}/></label><label className="wide">UPI transaction reference<input required name="paymentReference" value={form.paymentReference} onChange={e=>update(e.target.name,e.target.value)} placeholder="UPI / UTR reference"/></label><label className="wide proof-picker">Payment confirmation image<input required type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>void selectProof(e.target.files?.[0]??null)}/><small>On mobile, choose Camera to photograph the confirmation. Large images are automatically compressed for private storage.</small>{optimizing&&<strong>Optimizing image…</strong>}{proof&&<strong>Ready: {proof.name} ({Math.ceil(proof.size/1024)} KB)</strong>}</label></div></fieldset>
<fieldset><legend><span>3</span>Annadaanam attendance</legend><div className="field-grid"><label>Adults / elders<input required name="adultCount" type="number" min="0" max="30" value={form.adultCount} onChange={e=>update(e.target.name,e.target.value)}/></label><label>Children<input required name="childCount" type="number" min="0" max="30" value={form.childCount} onChange={e=>update(e.target.name,e.target.value)}/></label><label className="wide">Notes <span className="optional">optional</span><textarea name="notes" rows={3} value={form.notes} onChange={e=>update(e.target.name,e.target.value)}/></label></div></fieldset>
<label className="consent"><input type="checkbox" checked={form.publicNameConsent} onChange={e=>update("publicNameConsent",e.target.checked)}/><span><strong>Show resident name in verified donor list</strong><small>Block, flat, phone and payment proof remain private.</small></span></label>{error&&<p className="form-error">{error}</p>}</div><aside className="form-summary"><span className="summary-label">Donation summary</span><div><span>Festival</span><strong>{currency(Number(form.mainDonation)||0)}</strong></div><div><span>Annadaanam</span><strong>{currency(Number(form.annadaanamDonation)||0)}</strong></div><div className="summary-total"><span>Total</span><strong>{currency(total)}</strong></div><button className="button primary full" disabled={busy||optimizing}>{optimizing?"Optimizing image…":busy?"Saving…":"Save donation"}</button><p>UPI only. Payment remains pending until an admin verifies it.</p></aside></form>}
