"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BLOCKS } from "../../lib/constants";
import { eligiblePrasadamDays, prasadamDateLabel, PRASADAM_SEVA_DAYS } from "../../lib/prasadam";

type Offering={id:string;referenceNo:string;blockNo:string;flatNo:string;residentName:string;phone:string;offeringDate:string;dayNumber:number;prasadamName:string;portions:number;notes:string;status:"submitted"|"confirmed"|"cancelled";createdAt:string};
type User={role:"admin"|"block"|"cultural";blockNo:string|null};

export function PrasadamSevaDashboard(){
  const [rows,setRows]=useState<Offering[]>([]);const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [query,setQuery]=useState("");const [date,setDate]=useState("");const [block,setBlock]=useState("");const [status,setStatus]=useState("");const [busy,setBusy]=useState("");const [editing,setEditing]=useState<Offering|null>(null);
  async function load(){setLoading(true);setError("");try{const response=await fetch("/api/prasadam-offerings",{cache:"no-store"});const payload=await response.json() as {error?:string;offerings?:Offering[];user?:User};if(!response.ok)throw new Error(payload.error??"Unable to load offerings.");setRows(payload.offerings??[]);setUser(payload.user??null);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load offerings.");}finally{setLoading(false);}}
  useEffect(()=>{let active=true;fetch("/api/prasadam-offerings",{cache:"no-store"}).then(async(response)=>{const payload=await response.json() as {error?:string;offerings?:Offering[];user?:User};if(!response.ok)throw new Error(payload.error??"Unable to load offerings.");if(active){setRows(payload.offerings??[]);setUser(payload.user??null);}}).catch((caught)=>active&&setError(caught instanceof Error?caught.message:"Unable to load offerings.")).finally(()=>active&&setLoading(false));return()=>{active=false;};},[]);
  const visible=useMemo(()=>rows.filter((row)=>{const haystack=`${row.residentName} ${row.blockNo} ${row.flatNo} ${row.phone} ${row.prasadamName} ${row.referenceNo}`.toLowerCase();return(!query||haystack.includes(query.toLowerCase()))&&(!date||row.offeringDate===date)&&(!block||row.blockNo===block)&&(!status||row.status===status);}),[rows,query,date,block,status]);
  const active=visible.filter((row)=>row.status!=="cancelled");const totalPortions=active.reduce((sum,row)=>sum+Number(row.portions),0);const households=new Set(active.map((row)=>`${row.blockNo}-${row.flatNo}`)).size;
  const scheduleDays=user?.role==="block"?eligiblePrasadamDays(user.blockNo??""):PRASADAM_SEVA_DAYS;
  const grouped=scheduleDays.map((day)=>({day,rows:visible.filter((row)=>row.offeringDate===day.date)})).filter((group)=>group.rows.length||(!date&&!query&&!block&&!status));
  const exportUrl=useMemo(()=>{const params=new URLSearchParams();if(query.trim())params.set("q",query.trim());if(date)params.set("date",date);if(block)params.set("block",block);if(status)params.set("status",status);return `/api/prasadam-offerings/export?${params}`;},[query,date,block,status]);
  async function changeStatus(item:Offering,next:Offering["status"]){setBusy(item.id);setError("");try{const response=await fetch("/api/prasadam-offerings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,status:next})});const payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??"Unable to update the offering.");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Unable to update the offering.");}finally{setBusy("");}}
  async function saveEdit(event:FormEvent){event.preventDefault();if(!editing)return;setBusy(editing.id);setError("");try{const response=await fetch("/api/prasadam-offerings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...editing,action:"edit"})});const payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??"Unable to save the corrections.");setEditing(null);await load();}catch(caught){setError(caught instanceof Error?caught.message:"Unable to save the corrections.");}finally{setBusy("");}}
  function printPlan(){document.body.classList.add("printing-prasadam-plan");const cleanup=()=>document.body.classList.remove("printing-prasadam-plan");window.addEventListener("afterprint",cleanup,{once:true});window.print();setTimeout(cleanup,1500);}
  return <section className="wrap prasadam-dashboard">
    <header className="workspace-heading"><div><div className="eyebrow"><span/>Pooja coordination workspace</div><h1>Prasadam Seva Plan</h1><p>Review day-wise offerings, expected portions and resident contact details.</p></div><a className="button primary" href="/prasadam-seva">+ Record Offering</a></header>
    <div className="prasadam-stat-grid"><article><span>Active offerings</span><strong>{active.length}</strong></article><article><span>Participating flats</span><strong>{households}</strong></article><article><span>Expected portions</span><strong>{totalPortions.toLocaleString("en-IN")}</strong></article><article><span>Awaiting confirmation</span><strong>{active.filter((row)=>row.status==="submitted").length}</strong></article></div>
    <div className="workspace-toolbar prasadam-toolbar no-print"><input aria-label="Search offerings" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search name, flat, mobile or prasadam"/><select aria-label="Filter by date" value={date} onChange={(event)=>setDate(event.target.value)}><option value="">All seva days</option>{PRASADAM_SEVA_DAYS.map((day)=><option key={day.date} value={day.date}>Day {day.day} · {prasadamDateLabel(day.date)}</option>)}</select>{user?.role!=="block"&&<select aria-label="Filter by block" value={block} onChange={(event)=>setBlock(event.target.value)}><option value="">All blocks</option>{BLOCKS.map((item)=><option key={item}>{item}</option>)}</select>}<select aria-label="Filter by status" value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">All statuses</option><option value="submitted">Awaiting confirmation</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option></select><a className={`button quiet${visible.length?"":" disabled"}`} aria-disabled={!visible.length} href={visible.length?exportUrl:undefined}>Download Excel</a><button className="button primary" onClick={printPlan} disabled={!visible.length}>Print / Save as PDF</button></div>
    {error&&<p className="form-error">{error}</p>}{loading&&<div className="empty-state"><p>Loading Prasadam Seva plan…</p></div>}
    {!loading&&!visible.length&&<div className="empty-state"><p>No offerings match these filters.</p></div>}
    {!loading&&grouped.map(({day,rows:dayRows})=><section className="prasadam-day-group" key={day.date}><header><div><span>Day {day.day}</span><h2>{prasadamDateLabel(day.date)}</h2><p>{day.block==="OPEN"?"Open offering · All blocks":`Assigned to Block ${day.block}`}</p></div><div><strong>{dayRows.filter((row)=>row.status!=="cancelled").reduce((sum,row)=>sum+Number(row.portions),0).toLocaleString("en-IN")}</strong><span>planned portions</span></div></header>{dayRows.length?<div className="prasadam-entry-grid">{dayRows.map((item)=><article className={item.status==="cancelled"?"cancelled":""} key={item.id}><header><div><span className={`status ${item.status}`}>{item.status==="submitted"?"Awaiting confirmation":item.status}</span><small>{item.referenceNo}</small></div><strong>{item.portions} portions</strong></header><h3>{item.prasadamName}</h3><p><strong>{item.residentName}</strong><span>Block {item.blockNo} · Flat {item.flatNo}</span></p><a href={`tel:+91${item.phone}`}>+91 {item.phone}</a>{item.notes&&<blockquote>{item.notes}</blockquote>}<div className="card-actions">{user?.role==="admin"&&<button className="button quiet" disabled={busy===item.id} onClick={()=>setEditing({...item})}>Edit Offering</button>}{item.status!=="confirmed"&&item.status!=="cancelled"&&<button className="button primary" disabled={busy===item.id} onClick={()=>void changeStatus(item,"confirmed")}>Confirm</button>}{item.status!=="cancelled"&&<button className="button quiet" disabled={busy===item.id} onClick={()=>void changeStatus(item,"cancelled")}>Cancel</button>}{item.status==="cancelled"&&<button className="button quiet" disabled={busy===item.id} onClick={()=>void changeStatus(item,"submitted")}>Restore</button>}</div></article>)}</div>:<div className="empty-state compact"><p>No offerings registered for this day.</p></div>}</section>)}
    {editing&&<div className="dialog-backdrop" role="presentation"><section className="dialog prasadam-edit-dialog" role="dialog" aria-modal="true" aria-labelledby="edit-prasadam-title"><button className="dialog-close" type="button" aria-label="Close" onClick={()=>setEditing(null)}>×</button><div className="eyebrow"><span/>Correct offering details</div><h2 id="edit-prasadam-title">Edit Prasadam Offering</h2><form onSubmit={(event)=>void saveEdit(event)}><div className="field-grid"><label>Block<select required value={editing.blockNo} onChange={(event)=>setEditing({...editing,blockNo:event.target.value,offeringDate:""})}>{BLOCKS.map((item)=><option key={item} value={item}>Block {item}</option>)}</select></label><label>Flat Number<input required value={editing.flatNo} onChange={(event)=>setEditing({...editing,flatNo:event.target.value.toUpperCase().replace(/[\s-]/g,"")})}/></label><label>Resident Name<input required maxLength={100} value={editing.residentName} onChange={(event)=>setEditing({...editing,residentName:event.target.value})}/></label><label>Mobile Number<input required inputMode="numeric" pattern="[0-9]{10}" maxLength={10} value={editing.phone} onChange={(event)=>setEditing({...editing,phone:event.target.value.replace(/\D/g,"").slice(0,10)})}/></label><label>Offering Date<select required value={editing.offeringDate} onChange={(event)=>setEditing({...editing,offeringDate:event.target.value})}><option value="" disabled>Select eligible date</option>{eligiblePrasadamDays(editing.blockNo).map((day)=><option key={day.date} value={day.date}>Day {day.day} · {prasadamDateLabel(day.date)}</option>)}</select></label><label>Portions<input required type="number" min={1} max={2000} value={editing.portions} onChange={(event)=>setEditing({...editing,portions:Number(event.target.value)})}/></label></div><label>Prasadam<input required maxLength={160} value={editing.prasadamName} onChange={(event)=>setEditing({...editing,prasadamName:event.target.value})}/></label><label>Notes<textarea maxLength={500} value={editing.notes} onChange={(event)=>setEditing({...editing,notes:event.target.value})}/></label><div className="dialog-actions"><button className="button quiet" type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="button primary" disabled={busy===editing.id}>Save Corrections</button></div></form></section></div>}
  </section>;
}
