"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CULTURAL_CATEGORIES, CULTURAL_STATUSES, CULTURAL_STATUS_LABELS } from "../lib/cultural";

type Participant={name:string;age:number;blockNo:string;flatNo:string};
type Programme={id:string;referenceNo:string;title:string;performanceType:string;category:string;participantDetails:string;coordinator:string;contactName:string;contactPhone:string;programmeDate:string;startTime:string;durationMinutes:number;status:string;backgroundMusic:number;hasAudio:number;audioName:string|null;audioArrangement:"upload"|"own_device";deviceDetails:string;stageRequirements:string;propsRequirements:string;setupMinutes:number;source:string;createdBy:string;createdAt:string;notes:string};
type ProgrammeUser={portalOwner?:boolean};

function participants(item:Programme):Participant[]{try{const parsed=JSON.parse(item.participantDetails);return Array.isArray(parsed)?parsed:[];}catch{return item.participantDetails?[{name:item.participantDetails,age:0,blockNo:"",flatNo:""}]:[];}}
function programmeDateLabel(value:string){return new Date(`${value}T00:00:00`).toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"});}
function programmeTimeLabel(value:string){const [hour,minute]=value.split(":").map(Number);return new Date(2000,0,1,hour,minute).toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit"});}
function programmeEndTime(value:string,duration:number){const [hour,minute]=value.split(":").map(Number);const date=new Date(2000,0,1,hour,minute+duration);return date.toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit"});}

export function CulturalProgramme(){
  const [items,setItems]=useState<Programme[]>([]);const [user,setUser]=useState<ProgrammeUser|null>(null);const [reviewing,setReviewing]=useState<Programme|null>(null);const [filter,setFilter]=useState("");const [statusFilter,setStatusFilter]=useState("active");const [categoryFilter,setCategoryFilter]=useState("all");const [typeFilter,setTypeFilter]=useState("all");const [view,setView]=useState<"registrations"|"schedule">("registrations");const [dateFilter,setDateFilter]=useState("all");const [error,setError]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/cultural/programmes",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to load cultural registrations.");setItems(body.programmes??[]);setUser(body.user??null);},[]);
  useEffect(()=>{let active=true;fetch("/api/cultural/programmes",{cache:"no-store"}).then(async(response)=>({response,body:await response.json()})).then(({response,body})=>{if(!active)return;if(!response.ok)setError(body.error??"Unable to load cultural registrations.");else{setItems(body.programmes??[]);setUser(body.user??null);}}).catch(()=>active&&setError("Unable to load cultural registrations."));return()=>{active=false;};},[]);
  const counts=useMemo(()=>Object.fromEntries(CULTURAL_STATUSES.map((status)=>[status,items.filter((item)=>item.status===status).length])),[items]);
  const visible=useMemo(()=>items.filter((item)=>{const searchable=`${item.referenceNo} ${item.title} ${item.category} ${item.participantDetails} ${item.contactName} ${item.contactPhone}`.toLowerCase();const statusMatches=statusFilter==="all"||(statusFilter==="active"?item.status!=="withdrawn"&&item.status!=="completed":item.status===statusFilter);const categoryMatches=categoryFilter==="all"||item.category===categoryFilter;const typeMatches=typeFilter==="all"||item.performanceType===typeFilter;return statusMatches&&categoryMatches&&typeMatches&&searchable.includes(filter.toLowerCase());}),[items,filter,statusFilter,categoryFilter,typeFilter]);
  const scheduled=useMemo(()=>items.filter((item)=>item.status==="scheduled"&&item.programmeDate&&item.startTime&&(categoryFilter==="all"||item.category===categoryFilter)&&(typeFilter==="all"||item.performanceType===typeFilter)).sort((left,right)=>`${left.programmeDate} ${left.startTime}`.localeCompare(`${right.programmeDate} ${right.startTime}`)),[items,categoryFilter,typeFilter]);
  const scheduleDates=useMemo(()=>[...new Set(scheduled.map((item)=>item.programmeDate))],[scheduled]);
  const scheduleDays=useMemo(()=>scheduleDates.filter((date)=>dateFilter==="all"||date===dateFilter).map((date)=>({date,items:scheduled.filter((item)=>item.programmeDate===date)})),[scheduled,scheduleDates,dateFilter]);
  const registrationExportUrl=useMemo(()=>{const params=new URLSearchParams({status:statusFilter});if(filter.trim())params.set("q",filter.trim());if(categoryFilter!=="all")params.set("category",categoryFilter);if(typeFilter!=="all")params.set("type",typeFilter);return `/api/cultural/programmes/export?${params}`;},[filter,statusFilter,categoryFilter,typeFilter]);
  const scheduleExportUrl=useMemo(()=>{const params=new URLSearchParams({scheduled:"true"});if(dateFilter!=="all")params.set("date",dateFilter);if(categoryFilter!=="all")params.set("category",categoryFilter);if(typeFilter!=="all")params.set("type",typeFilter);return `/api/cultural/programmes/export?${params}`;},[dateFilter,categoryFilter,typeFilter]);
  async function withdraw(item:Programme){if(!confirm(`Mark “${item.title}” as withdrawn? The record and its audio track will be retained.`))return;const response=await fetch(`/api/cultural/programmes?id=${item.id}`,{method:"DELETE"});const body=await response.json();if(!response.ok){setError(body.error??"Unable to withdraw the entry.");return;}await load();}
  async function recycle(item:Programme){if(!confirm(`Move “${item.title}” to the Recycle Bin? The Portal Admin can restore it later.`))return;const response=await fetch(`/api/cultural/programmes?id=${item.id}&recycle=true`,{method:"DELETE"});const body=await response.json();if(!response.ok){setError(body.error??"Unable to move the registration to the Recycle Bin.");return;}await load();}
  function printSchedule(){document.body.classList.add("printing-cultural-schedule");const cleanup=()=>document.body.classList.remove("printing-cultural-schedule");window.addEventListener("afterprint",cleanup,{once:true});window.print();setTimeout(cleanup,1500);}
  return <section className="wrap workspace-shell">
    <div className="workspace-heading"><div><div className="eyebrow"><span/>Cultural committee workspace</div><h1>{view==="schedule"?"Programme Schedule":"Cultural Registrations"}</h1><p>{view==="schedule"?"Use the day-wise run sheet during the event or save a committee-ready PDF.":"Review resident and volunteer entries, coordinate requirements and build the programme schedule."}</p></div><a className="button primary no-print" href="/cultural/register">+ Record Registration</a></div>
    {error&&<p className="form-error">{error}</p>}
    <div className="cultural-status-summary"><article><span>New</span><strong>{counts.submitted??0}</strong></article><article><span>Under Review</span><strong>{counts.under_review??0}</strong></article><article><span>Approved</span><strong>{counts.approved??0}</strong></article><article><span>Scheduled</span><strong>{counts.scheduled??0}</strong></article><article><span>Waitlisted</span><strong>{counts.waitlisted??0}</strong></article></div>
    <div className="cultural-view-switch" role="group" aria-label="Cultural programme view"><button className={view==="registrations"?"active":""} onClick={()=>setView("registrations")}>Registration Review</button><button className={view==="schedule"?"active":""} onClick={()=>setView("schedule")}>Day-wise Schedule <span>{scheduled.length}</span></button></div>
    {view==="registrations"?<>
      <div className="workspace-toolbar cultural-toolbar"><input aria-label="Search cultural registrations" placeholder="Search title, participant, contact or reference" value={filter} onChange={(event)=>setFilter(event.target.value)}/><select aria-label="Filter cultural registrations by status" value={statusFilter} onChange={(event)=>setStatusFilter(event.target.value)}><option value="active">Active registrations</option><option value="all">All registrations</option>{CULTURAL_STATUSES.map((status)=><option value={status} key={status}>{CULTURAL_STATUS_LABELS[status]}</option>)}</select><select aria-label="Filter cultural registrations by category" value={categoryFilter} onChange={(event)=>{setCategoryFilter(event.target.value);setDateFilter("all");}}><option value="all">All Categories</option>{CULTURAL_CATEGORIES.map((category)=><option value={category} key={category}>{category}</option>)}</select><select aria-label="Filter cultural registrations by performance type" value={typeFilter} onChange={(event)=>setTypeFilter(event.target.value)}><option value="all">All Types</option><option value="solo">Solo</option><option value="group">Group</option></select><strong>{visible.length} entr{visible.length===1?"y":"ies"}</strong><a className="button quiet" href={registrationExportUrl}>Export Registrations (.xlsx)</a></div>
      <div className="programme-grid">{visible.map((item)=>{const people=participants(item);const isKolatam=item.category==="Kolatam";return <article key={item.id} className="programme-card cultural-registration-card"><header><span className={`status ${item.status}`}>{CULTURAL_STATUS_LABELS[item.status as keyof typeof CULTURAL_STATUS_LABELS]??item.status.replaceAll("_"," ")}</span><small>{item.performanceType} · {item.category}</small></header><h2>{item.title}</h2><span className="registration-reference">{item.referenceNo}</span><div className="participant-summary">{people.map((person,index)=><p key={`${person.name}-${index}`}><strong>{person.name}</strong><span>{person.age?`Age ${person.age} · `:""}{person.blockNo?`Block ${person.blockNo} · Flat ${person.flatNo}`:"Legacy entry"}</span></p>)}</div><dl><div><dt>Point of contact</dt><dd>{item.contactName||"—"}{item.contactPhone?<small>+91 {item.contactPhone}</small>:null}</dd></div>{!isKolatam&&<div><dt>Duration</dt><dd>{item.durationMinutes} min</dd></div>}{!isKolatam&&<div><dt>Audio arrangement</dt><dd>{item.audioArrangement==="own_device"?"Performer’s device":"Uploaded song"}{item.audioArrangement==="own_device"&&item.deviceDetails?<small>{item.deviceDetails}</small>:null}</dd></div>}<div><dt>Schedule</dt><dd>{item.programmeDate||"To be scheduled"}{item.startTime?` · ${item.startTime}`:""}</dd></div><div><dt>Source</dt><dd>{item.source==="resident"?"Resident form":"Volunteer entry"}</dd></div></dl>{item.audioArrangement==="upload"&&item.hasAudio?<a className="button quiet full" href={`/api/cultural/audio/${item.id}`} target="_blank" rel="noreferrer">Open Audio Track{item.audioName?` · ${item.audioName}`:""}</a>:null}<a className="button quiet full cultural-edit-action" href={`/cultural/register?programme=${encodeURIComponent(item.id)}`}>Edit Entry Details</a><div className="card-actions"><button className="button primary" onClick={()=>setReviewing(item)}>Review / Schedule</button>{item.status!=="withdrawn"&&<button className="button danger-button" onClick={()=>void withdraw(item)}>Withdraw</button>}</div>{user?.portalOwner&&<button className="button danger-button full recycle-action" onClick={()=>void recycle(item)}>Move to Recycle Bin</button>}</article>;})}</div>
      {!visible.length&&<div className="admin-card empty-state"><p>No cultural registrations match this view.</p></div>}
    </>:<>
      <div className="workspace-toolbar cultural-schedule-toolbar no-print"><label>Date<select aria-label="Filter scheduled performances by date" value={dateFilter} onChange={(event)=>setDateFilter(event.target.value)}><option value="all">All scheduled dates</option>{scheduleDates.map((date)=><option key={date} value={date}>{programmeDateLabel(date)}</option>)}</select></label><label>Category<select aria-label="Filter scheduled performances by category" value={categoryFilter} onChange={(event)=>{setCategoryFilter(event.target.value);setDateFilter("all");}}><option value="all">All Categories</option>{CULTURAL_CATEGORIES.map((category)=><option value={category} key={category}>{category}</option>)}</select></label><label>Type<select aria-label="Filter scheduled performances by performance type" value={typeFilter} onChange={(event)=>setTypeFilter(event.target.value)}><option value="all">All Types</option><option value="solo">Solo</option><option value="group">Group</option></select></label><div><strong>{scheduleDays.reduce((total,day)=>total+day.items.length,0)} scheduled performance(s)</strong><a className="button quiet" href={scheduleExportUrl}>Export Schedule (.xlsx)</a><button className="button primary" disabled={!scheduleDays.length} onClick={printSchedule}>Print / Save as PDF</button></div></div>
      <div className="cultural-run-sheet">
        <header className="run-sheet-title"><span>Hallmark Skyrena · Ganesh Chaturthi 2026</span><h2>Cultural Programme — Run of Show</h2><p>{dateFilter==="all"?"Day-wise performance plan":programmeDateLabel(dateFilter)}</p></header>
        {scheduleDays.map((day)=><section className="run-sheet-day" key={day.date}><header><div><span>Programme day</span><h3>{programmeDateLabel(day.date)}</h3></div><div><strong>{day.items.length}</strong><span>performances</span><strong>{day.items.reduce((total,item)=>total+item.durationMinutes,0)} min</strong><span>planned</span></div></header><div className="run-sheet-head"><span>Time</span><span>Performance &amp; participants</span><span>Category</span><span>Show notes</span></div>{day.items.map((item,index)=>{const people=participants(item);const isKolatam=item.category==="Kolatam";return <article className="run-sheet-row" key={item.id}><div className="run-order"><b>{String(index+1).padStart(2,"0")}</b><strong>{programmeTimeLabel(item.startTime)}</strong>{!isKolatam&&<small>to {programmeEndTime(item.startTime,item.durationMinutes)}</small>}</div><div className="run-performance"><strong>{item.title}</strong><span>{people.map((person)=>person.name).join(", ")}</span><small>{people.map((person)=>`${person.blockNo}-${person.flatNo}`).join(" · ")} · {item.referenceNo}</small></div><div className="run-category"><strong>{item.category}</strong><span>{item.performanceType}{!isKolatam&&` · ${item.durationMinutes} min`}</span></div><div className="run-notes">{!isKolatam&&<span>{item.audioArrangement==="own_device"?"♫ Performer’s own device":"♫ Uploaded song"}</span>}{!isKolatam&&item.audioArrangement==="own_device"&&item.deviceDetails?<small>{item.deviceDetails}</small>:null}<small>{item.coordinator?`Coordinator: ${item.coordinator}`:"Coordinator not assigned"}</small>{item.audioArrangement==="upload"&&item.hasAudio?<a href={`/api/cultural/audio/${item.id}`} target="_blank" rel="noreferrer">Open audio</a>:null}</div></article>;})}</section>)}
        {!scheduleDays.length&&<div className="admin-card empty-state"><p>No scheduled performances are available for this date. Use “Review / Schedule” to assign a date and start time.</p></div>}
        {scheduleDays.length>0&&<footer className="run-sheet-footer">Prepared from the Hallmark Skyrena Festival Portal · Timings are shown in chronological order.</footer>}
      </div>
    </>}
    {reviewing&&<ReviewDialog item={reviewing} close={()=>setReviewing(null)} saved={async()=>{setReviewing(null);await load();}}/>}
  </section>;
}

function ReviewDialog({item,close,saved}:{item:Programme;close:()=>void;saved:()=>Promise<void>}){
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const body={...Object.fromEntries(new FormData(event.currentTarget)),id:item.id};try{const response=await fetch("/api/cultural/programmes",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Unable to update the registration.");await saved();}catch(caught){setError(caught instanceof Error?caught.message:"Unable to update the registration.");setBusy(false);}}
  return <div className="dialog-backdrop" onMouseDown={(event)=>{if(!busy&&event.target===event.currentTarget)close();}}><div className="dialog programme-dialog review-programme-dialog" role="dialog" aria-modal="true"><button className="dialog-close" disabled={busy} onClick={close}>×</button><span className="card-kicker">{item.referenceNo}</span><h2>Review {item.title}</h2><form onSubmit={submit}><label>Status<select name="status" required defaultValue={item.status}>{CULTURAL_STATUSES.map((status)=><option key={status} value={status}>{CULTURAL_STATUS_LABELS[status]}</option>)}</select></label><label>Committee Coordinator <span className="optional">optional</span><input name="coordinator" defaultValue={item.coordinator}/></label><div className="field-grid"><label>Programme Date <span className="optional">required when scheduled</span><input name="programmeDate" type="date" defaultValue={item.programmeDate}/></label><label>Start Time <span className="optional">required when scheduled</span><input name="startTime" type="time" defaultValue={item.startTime}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" className="button quiet" disabled={busy} onClick={close}>Cancel</button><button className="button primary" disabled={busy}>{busy?"Saving…":"Save Review"}</button></div></form></div></div>;
}
