"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { BLOCKS } from "../lib/constants";

type Programme = { id:string;title:string;category:string;participantDetails:string;coordinator:string;blockNo:string;flatNo:string;programmeDate:string;startTime:string;durationMinutes:number;status:string;notes:string;createdBy:string };
const CATEGORIES = ["Dance", "Music", "Drama / Skit", "Devotional", "Kids Activity", "Games", "Anchoring", "Other"];

export function CulturalProgramme() {
  const [items,setItems]=useState<Programme[]>([]); const [editing,setEditing]=useState<Programme|"new"|null>(null); const [filter,setFilter]=useState(""); const [error,setError]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/cultural/programmes");const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to load cultural programme.");setItems(body.programmes);},[]);
  useEffect(()=>{let active=true;fetch("/api/cultural/programmes").then(async(response)=>({response,body:await response.json()})).then(({response,body})=>{if(!active)return;if(!response.ok)setError(body.error??"Unable to load cultural programme.");else setItems(body.programmes);}).catch(()=>active&&setError("Unable to load cultural programme."));return()=>{active=false;};},[]);
  const visible=useMemo(()=>items.filter((item)=>`${item.title} ${item.category} ${item.participantDetails} ${item.coordinator} ${item.blockNo} ${item.flatNo}`.toLowerCase().includes(filter.toLowerCase())),[items,filter]);
  async function remove(item:Programme){if(!confirm(`Delete “${item.title}”?`))return;const response=await fetch(`/api/cultural/programmes?id=${item.id}`,{method:"DELETE"});if(!response.ok){const body=await response.json();setError(body.error);return;}await load();}
  return <section className="wrap workspace-shell">
    <div className="workspace-heading"><div><div className="eyebrow"><span/>Cultural committee workspace</div><h1>Cultural Programme</h1><p>Plan performances, participants, coordinators and the running order in one place.</p></div><button className="button primary" onClick={()=>setEditing("new")}>+ Add Programme</button></div>
    {error&&<p className="form-error">{error}</p>}
    <div className="workspace-toolbar"><input aria-label="Search cultural programmes" placeholder="Search programme, participant or coordinator" value={filter} onChange={(event)=>setFilter(event.target.value)}/><strong>{visible.length} programme{visible.length===1?"":"s"}</strong></div>
    <div className="programme-grid">{visible.map((item)=><article key={item.id} className="programme-card"><header><span className={`status ${item.status}`}>{item.status.replace("_"," ")}</span><small>{item.category}</small></header><h2>{item.title}</h2><p>{item.participantDetails||"Participants to be confirmed"}</p><dl><div><dt>Coordinator</dt><dd>{item.coordinator||"—"}</dd></div><div><dt>Resident</dt><dd>{item.blockNo?`Block ${item.blockNo}${item.flatNo?` · ${item.flatNo}`:""}`:"—"}</dd></div><div><dt>Schedule</dt><dd>{item.programmeDate||"To be scheduled"}{item.startTime?` · ${item.startTime}`:""}</dd></div><div><dt>Duration</dt><dd>{item.durationMinutes} min</dd></div></dl>{item.notes&&<p className="programme-notes">{item.notes}</p>}<div className="card-actions"><button className="button quiet" onClick={()=>setEditing(item)}>Edit</button><button className="button danger-button" onClick={()=>void remove(item)}>Delete</button></div></article>)}</div>
    {!visible.length&&<div className="admin-card empty-state"><p>No cultural programmes match this view.</p></div>}
    {editing&&<ProgrammeDialog item={editing==="new"?null:editing} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await load();}}/>}
  </section>;
}

function ProgrammeDialog({item,close,saved}:{item:Programme|null;close:()=>void;saved:()=>Promise<void>}) {
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const body=Object.fromEntries(new FormData(event.currentTarget));if(item)body.id=item.id;const response=await fetch("/api/cultural/programmes",{method:item?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok){setError(payload.error);setBusy(false);return;}await saved();}
  return <div className="dialog-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)close();}}><div className="dialog programme-dialog" role="dialog" aria-modal="true"><button className="dialog-close" onClick={close}>×</button><span className="card-kicker">Cultural programme</span><h2>{item?"Edit Programme":"Add Programme"}</h2><form onSubmit={submit}><div className="field-grid"><label className="wide">Programme / Performance Name<input name="title" required defaultValue={item?.title}/></label><label>Category<select name="category" defaultValue={item?.category??CATEGORIES[0]}>{CATEGORIES.map((category)=><option key={category}>{category}</option>)}</select></label><label>Status<select name="status" defaultValue={item?.status??"proposed"}><option value="proposed">Proposed</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label className="wide">Participants / Group Details<textarea name="participantDetails" rows={3} defaultValue={item?.participantDetails}/></label><label>Coordinator<input name="coordinator" defaultValue={item?.coordinator}/></label><label>Block<select name="blockNo" defaultValue={item?.blockNo??""}><option value="">Not applicable</option>{BLOCKS.map((block)=><option key={block}>{block}</option>)}</select></label><label>Flat Number<input name="flatNo" defaultValue={item?.flatNo}/></label><label>Programme Date<input name="programmeDate" type="date" defaultValue={item?.programmeDate}/></label><label>Start Time<input name="startTime" type="time" defaultValue={item?.startTime}/></label><label>Duration (minutes)<input name="durationMinutes" type="number" min="1" max="240" defaultValue={item?.durationMinutes??10}/></label><label className="wide">Notes<textarea name="notes" rows={3} defaultValue={item?.notes}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" className="button quiet" onClick={close}>Cancel</button><button className="button primary" disabled={busy}>{busy?"Saving…":"Save Programme"}</button></div></form></div></div>;
}
